config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'site#home'
  scope module: :api do
     scope module: :v1 do
       resources :company_groups , :defaults => { :format => 'json' } , :only => [:index]
       resources :companies , :defaults => { :format => 'json' }, :only => [:index, :show]
       resources :cinema , :defaults => { :format => 'json' }, :only => [:index, :show]
       resources :movies , :defaults => { :format => 'json' }, :only => [:index, :show]
       resources :cinema_baners , :defaults => { :format => 'json' }, :only => [:index]
       resources :forum_groups , :defaults => { :format => 'json' } , :only => [:index]
       resources :forum_themes , :defaults => { :format => 'json' }, :only => [:index, :show, :create]
       resources :forum_message , :defaults => { :format => 'json' }, :only => [:create ,:destroy]
       resources :media_assets, :defaults => { :format => 'json' }, :only => [:create, :destroy]
       resources :ad_group_links, :defaults => { :format => 'json' }, :only => [:create, :destroy]
       resources :company_group_links, :defaults => { :format => 'json' }, :only => [:create, :destroy]
       resources :recreation_group_links, :defaults => { :format => 'json' }, :only => [:create, :destroy]
       resources :ads , :defaults => { :format => 'json' }, :only => [ :index, :create, :destroy, :show ]
       resources :ad_groups , :defaults => { :format => 'json' }, :only => [:index]
       resources :ad_kinds , :defaults => { :format => 'json' }, :only => [:index]
       resources :recreations , :defaults => { :format => 'json' }, :only => [:index, :show]
       resources :recreation_groups , :defaults => { :format => 'json' }, :only => [:index]
       resources :events , :defaults => { :format => 'json' }, :only => [:index, :show]
       resources :event_groups , :defaults => { :format => 'json' } , :only => [:index]
       resources :atms , :defaults => { :format => 'json' }, :only => [:index]
       resources :atm_groups , :defaults => { :format => 'json' } , :only => [:index]
       resources :rates , :defaults => { :format => 'json' }, :only => [:create,:index]
       resources :reviews , :defaults => { :format => 'json' }, :only => [:index , :create ,:destroy]
       resources :dictionaries , :defaults => { :format => 'json' }, :only => [:index]
       resources :stocks , :defaults => { :format => 'json' }, :only => [:index]
       resources :transports , :defaults => { :format => 'json' }, :only => [:index ,:show]
       resources :emergencies , :defaults => { :format => 'json' }, :only => [:index ,:show]
       resources :news_items , :defaults => { :format => 'json' }, :only => [:index]
       resources :lifestyles , :defaults => { :format => 'json' }, :only => [:index, :show]
       resources :lifestyle_groups , :defaults => { :format => 'json' }, :only => [:index]
       resources :tickets , :defaults => { :format => 'json' }, :only => [:index]
       resources :exchanges , :defaults => { :format => 'json' }, :only => [:index]
       resources :resources , :defaults => { :format => 'json' }, :only => [:index]
       resources :albums , :defaults => { :format => 'json' }, :only => [:index ,:show]
       resources :restaurants , :defaults => { :format => 'json' }, :only => [:index,:show]
       resources :restaurants_categories , :defaults => { :format => 'json' }, :only => [:index]
       resources :foods_list , :defaults => { :format => 'json' }, :only => [:index]
       resources :goods , :defaults => { :format => 'json' }, :only => [:index]
       resources :purchase , :defaults => { :format => 'json' }, :only => [:create]
       resources :notification_subscribe , :defaults => { :format => 'json' }, :only => [:create]
       resources :main_dashboard , :defaults => { :format => 'json' }, :only => [:index]
       resources :baners_dashboard , :defaults => { :format => 'json' }, :only => [:index]
       resources :notifications, :defaults => { :format => 'json' }, :only => [:index]
       resources :address_to_delivery , :defaults => { :format => 'json' }, :only => [:index,:create,:destroy,:update]
       resource :users, :defaults => { :format => 'json' }, :only => [] ,:path => "/" do
         get :address
       end
       resource :users, :defaults => { :format => 'json' }, :only => [:update] do
         post :login
       end
       resources :filters , :defaults => { :format => 'json' } , :only => [:index]
       resources :search , :defaults => { :format => 'json' } , :only => [:index]

     end
   end
end

app/views/admin/shared/_albums.html.haml
= form_for MediaAsset.new(:mediable_id => resource.id, :mediable_type => resource.class.to_s) , url: admin_media_assets_path do |f|
  = f.hidden_field :mediable_id
  = f.hidden_field :mediable_type
  = f.file_field :file
  = f.select :kind ,  resource.services.map{|a| a.name}
  = f.submit "Добавить", :style => "padding:5px;margin:5px;float:right;"

%table
  %tr
    %th Картинка
    %th Категория
  - resource.media_assets.each do |f|
    %tr
      %td=image_tag f.file_url, :width => 250
      %td= f.kind
      %td=link_to "Удалить", admin_media_asset_path(f), method: :delete, data: { confirm: "Удалить?"}

app/views/admin/shared/_atm.html.haml
= form_for AtmGroupLink.new(:atm_id => resource.id), url: admin_atm_group_links_path do |f|
  = f.hidden_field :atm_id
  = f.select :atm_group_id , AtmGroup.all.map{|a| [a.name , a.id]}
  = f.submit "Добавить", :style => "padding:5px;margin:5px;float:right;"

%table
  %tr
    %th name
  - resource.atm_group_links.each do |f|

    %tr
      %td=f.atm_group.name

      %td=link_to "Удалить", admin_atm_group_link_path(f), method: :delete, data: { confirm: "Удалить?"}

app/views/admin/shared/_company.html.haml
= form_for CompanyGroupLink.new(:company_id => resource.id), url: admin_company_group_links_path do |f|
  = f.hidden_field :company_id
  = f.select :company_group_id , CompanyGroup.all.map{|a| [a.name , a.id]}
  = f.submit "Добавить", :style => "padding:5px;margin:5px;float:right;"

%table
  %tr
    %th name
  - resource.company_group_links.each do |f|

    %tr
      %td=f.company_group.name

      %td=link_to "Удалить", admin_company_group_link_path(f), method: :delete, data: { confirm: "Удалить?"}

app/views/admin/shared/_event.html.haml
= form_for EventGroupLink.new(:event_id => resource.id), url: admin_event_group_links_path do |f|
  = f.hidden_field :event_id
  = f.select :event_group_id , EventGroup.all.map{|a| [a.name , a.id]}
  = f.submit "Добавить", :style => "padding:5px;margin:5px;float:right;"

%table
  %tr
    %th name
  - resource.event_group_links.each do |f|

    %tr
      %td=f.event_group.name

      %td=link_to "Удалить", admin_event_group_link_path(f), method: :delete, data: { confirm: "Удалить?"}

app/views/admin/shared/_food.html.haml
= form_for FoodGroupLink.new(:food_id => resource.id), url: admin_food_group_links_path do |f|
  = f.hidden_field :food_id
  = f.select :food_group_id , FoodGroup.all.map{|a| [a.name , a.id]}
  = f.submit "Добавить", :style => "padding:5px;margin:5px;float:right;"

%table
  %tr
    %th name
  - resource.food_group_links.each do |f|

    %tr
      %td=f.food_group.name

      %td=link_to "Удалить", admin_food_group_link_path(f), method: :delete, data: { confirm: "Удалить?"}

app/views/admin/shared/_food_item.html.haml
= link_to "Добавить", new_admin_food_item_path(:food_kind_id => resource.id ), :style => "padding:5px;margin:5px;float:right;"
%table
  %tr
    %th name
  - resource.food_items.each do |f|
    %tr
      %td= f.name
      %td=link_to "Посмотреть", admin_food_item_path(f)
      %td=link_to "Редактировать", edit_admin_food_item_path(f)
      %td=link_to "Удалить", admin_food_item_path(f), method: :delete, data: { confirm: "Удалить?"}

app/views/admin/shared/_food_kind.html.haml
= form_for FoodKind.new(:food_id => resource.id), url: admin_food_kinds_path do |f|
  = f.hidden_field :food_id
  = f.text_field :name , placeholder: "Введите название услуги"
  = f.submit "Добавить", :style => "padding:5px;margin:5px;float:right;"

%table
  %tr
    %th name
    %th the amount of food
  - resource.food_kinds.each do |f|
    %tr
      %td= f.name
      %td= f.food_items.count
      %td=link_to "Посмотреть", admin_food_kind_path(f)
      %td=link_to "Удалить", admin_food_kind_path(f), method: :delete, data: { confirm: "Удалить?"}

app/views/admin/shared/_forum.html.haml
= form_for ForumGroupLink.new(:forum_id => resource.id), url: admin_forum_group_links_path do |f|
  = f.hidden_field :forum_id
  = f.select :forum_group_id , ForumGroup.all.map{|a| [a.name , a.id]}
  = f.submit "Добавить", :style => "padding:5px;margin:5px;float:right;"

%table
  %tr
    %th name
  - resource.forum_group_links.each do |f|

    %tr
      %td=f.forum_group.name

      %td=link_to "Удалить", admin_forum_group_link_path(f), method: :delete, data: { confirm: "Удалить?"}

app/views/admin/shared/_lifestyle.html.haml
= form_for LifestyleGroupLink.new(:lifestyle_id => resource.id), url: admin_lifestyle_group_links_path do |f|
  = f.hidden_field :lifestyle_id
  = f.select :lifestyle_group_id , LifestyleGroup.all.map{|a| [a.name , a.id]}
  = f.submit "Добавить", :style => "padding:5px;margin:5px;float:right;"

%table
  %tr
    %th name
  - resource.lifestyle_group_links.each do |f|

    %tr
      %td=f.lifestyle_group.name

      %td=link_to "Удалить", admin_lifestyle_group_link_path(f), method: :delete, data: { confirm: "Удалить?"}

app/views/admin/shared/_map.html.haml
%script{:src => "https://maps.googleapis.com/maps/api/js?v=3.exp&libraries=drawing&key=AIzaSyCVH5JeUOWIHyRcozXXJJdGFS7T8rnOjTw"}
:javascript
  google.maps.Polygon.prototype.getBounds = function() {
      var bounds = new google.maps.LatLngBounds();
      var paths = this.getPaths();
      var path;        
      for (var i = 0; i < paths.getLength(); i++) {
          path = paths.getAt(i);
          for (var ii = 0; ii < path.getLength(); ii++) {
              bounds.extend(path.getAt(ii));
          }
      }
      return bounds;
  }


= javascript_include_tag :map_tools
= stylesheet_link_tag :map_tools
%div{"data-role" => "page"}
  #map-canvas

app/views/admin/shared/_media_assets.html.haml
= form_for MediaAsset.new(:mediable_id => resource.id, :mediable_type => resource.class.to_s) , url: admin_media_assets_path do |f|
  = f.hidden_field :mediable_id
  = f.hidden_field :mediable_type
  = f.file_field :file
  = f.select :kind ,  (resource.try(:media_assets_kinds) || %w(common)).map{|a| [I18n.t("#{a}"),a]}
  = f.submit "Добавить", :style => "padding:5px;margin:5px;float:right;"

%table
  %tr
    %th Картинка
    %th Категория
  - resource.media_assets.each do |f|
    %tr
      %td=image_tag f.file_url, :width => 250
      %td=I18n.t("#{f.kind}")
      %td=link_to "Удалить", admin_media_asset_path(f), method: :delete, data: { confirm: "Удалить?"}

app/views/admin/shared/_recreation.html.haml
= form_for RecreationGroupLink.new(:recreation_id => resource.id), url: admin_recreation_group_links_path do |f|
  = f.hidden_field :recreation_id
  = f.select :recreation_group_id , RecreationGroup.all.map{|a| [a.name , a.id]}
  = f.submit "Добавить", :style => "padding:5px;margin:5px;float:right;"

%table
  %tr
    %th name
  - resource.recreation_group_links.each do |f|

    %tr
      %td=f.recreation_group.name

      %td=link_to "Удалить", admin_recreation_group_link_path(f), method: :delete, data: { confirm: "Удалить?"}

app/views/admin/shared/_service.html.haml
= form_for Service.new(:serviceable_id => resource.id, :serviceable_type => resource.class.to_s) , url: admin_services_path do |f|
  = f.hidden_field :serviceable_id
  = f.hidden_field :serviceable_type
  = f.text_field :name , placeholder: "Введите название услуги"
  = f.submit "Добавить", :style => "padding:5px;margin:5px;float:right;"

%table
  %tr
    %th name
  - resource.services.each do |f|
    %tr
      %td= f.name
      %td=link_to "Удалить", admin_service_path(f), method: :delete, data: { confirm: "Удалить?"}

app/views/admin/shared/_staff.html.haml
= link_to "Добавить", new_admin_staff_path(:staffable_type => resource.class.to_s, :staffable_id => resource.id), :style => "padding:5px;margin:5px;float:right;"

%table
  %tr
    %th Фотография
    %th Имя
    %th Фамилия
    %th Профессия
  - resource.staffs.each do |f|

    %tr
      %td=image_tag f.media_assets.first.try(:file_url), :width => 50
      %td=f.name
      %td=f.surname
      %td=f.profession.name
      

      %td=link_to "Удалить", admin_staff_path(f), method: :delete, data: { confirm: "Удалить?"}